[package]
edition = "2018"
name = "napi-rs_simple-svg-parser"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"
svg-simple-parser = "0"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
